GET http://localhost:8888/application/local


###
GET http://localhost:8080

###
POST http://localhost:8080/actuator/refresh


###
GET http://localhost:8081

###
POST http://localhost:8081/actuator/refresh

### 테스트
GET http://localhost:8888/custom/dsjdfj/app1/beta
secretkey: sse

### 설정변경 적용
POST http://localhost:8888/custom-bus-refresh/dsjdfj/app1
###
POST http://localhost:8888/custom-bus-refresh/dsjdfj/application:8081
